php_snowflake.lo: /Users/lengbin/Documents/php_snowflake/php_snowflake.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/lengbin/Documents/php_snowflake $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/lengbin/Documents/php_snowflake/php_snowflake.c -o php_snowflake.lo 
$(phplibdir)/php_snowflake.la: ./php_snowflake.la
	$(LIBTOOL) --mode=install cp ./php_snowflake.la $(phplibdir)

./php_snowflake.la: $(shared_objects_php_snowflake) $(PHP_SNOWFLAKE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_php_snowflake) $(PHP_SNOWFLAKE_SHARED_LIBADD)

